"""Exporters for MOF Knowledge Graph"""
import json
from pathlib import Path
from typing import Optional

from mof_kg.models.schema import GraphData


class JSONExporter:
    """Export graph to JSON format"""

    def __init__(self, output_path: Path):
        self.output_path = output_path

    def export(self, data: GraphData) -> Path:
        """Export GraphData to JSON file"""
        output = {
            "nodes": data.nodes,
            "relationships": data.relationships,
            "metadata": {
                "node_count": len(data.nodes),
                "relationship_count": len(data.relationships),
            },
        }

        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        with self.output_path.open("w", encoding="utf-8") as f:
            json.dump(output, f, ensure_ascii=False, indent=2)

        return self.output_path


class CypherExporter:
    """Export graph to Neo4j Cypher statements"""

    def __init__(self, output_path: Path):
        self.output_path = output_path

    def export(self, data: GraphData) -> Path:
        """Export GraphData to Cypher script file"""
        lines = []

        # Add header
        lines.append("// MOF Knowledge Graph - Neo4j Cypher Script")
        lines.append("// Generated by MOF KG Builder")
        lines.append("")

        # Create constraints for unique node IDs
        lines.append("// Create constraints")
        lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (m:MOF) REQUIRE m.id IS UNIQUE;")
        lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (p:Precursor) REQUIRE p.id IS UNIQUE;")
        lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (m:Method) REQUIRE m.id IS UNIQUE;")
        lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (s:Stability) REQUIRE s.id IS UNIQUE;")
        lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (d:DOI) REQUIRE d.id IS UNIQUE;")
        lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (n:Name) REQUIRE n.id IS UNIQUE;")
        lines.append("")

        # Create nodes
        lines.append("// Create nodes")
        for node_id, node_data in data.nodes.items():
            node_type = node_data["type"]
            attrs = node_data["attributes"]

            # Build Cypher MERGE statement
            props = {"id": node_id}
            props.update(attrs)

            # Escape string values
            props_str = self._format_properties(props)
            lines.append(f"MERGE (:{node_type} {props_str});")

        lines.append("")

        # Create relationships
        lines.append("// Create relationships")
        for rel in data.relationships:
            from_id = rel["from"]
            to_id = rel["to"]
            rel_type = rel["type"]

            # Build MATCH and CREATE statements
            lines.append(f"MATCH (a {{id: '{from_id}'}}), (b {{id: '{to_id}'}})")
            lines.append(f"MERGE (a)-[:{rel_type}]->(b);")

        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        with self.output_path.open("w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return self.output_path

    def _format_properties(self, props: dict) -> str:
        """Format properties dict as Cypher map"""
        items = []
        for k, v in props.items():
            if v is None:
                continue
            elif isinstance(v, str):
                # Escape single quotes
                v_escaped = v.replace("'", "\\'")
                items.append(f"{k}: '{v_escaped}'")
            elif isinstance(v, bool):
                items.append(f"{k}: {str(v).lower()}")
            else:
                items.append(f"{k}: {v}")
        return "{" + ", ".join(items) + "}"


class GraphMLExporter:
    """Export graph to GraphML format (for visualization tools)"""

    def __init__(self, output_path: Path):
        self.output_path = output_path

    def export(self, data: GraphData) -> Path:
        """Export to GraphML format (requires lxml)"""
        try:
            import networkx as nx
        except ImportError:
            print("Warning: networkx not available for GraphML export")
            return self.output_path

        # Create NetworkX graph
        G = nx.DiGraph()

        # Add nodes (filter out None values and convert enums to strings)
        for node_id, node_data in data.nodes.items():
            attrs = {}
            for k, v in node_data["attributes"].items():
                if v is not None:
                    # Convert enums to strings
                    if hasattr(v, 'value'):
                        v = v.value
                    attrs[k] = v
            G.add_node(node_id, **attrs, node_type=node_data["type"])

        # Add edges
        for rel in data.relationships:
            G.add_edge(
                rel["from"],
                rel["to"],
                relationship_type=rel["type"],
            )

        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            nx.write_graphml(G, self.output_path)
        except Exception as e:
            print(f"Warning: GraphML export failed: {e}")
            return self.output_path

        return self.output_path